local ffi = require("ffi")

ffi.cdef([[
	typedef enum {
		 SDL_GL_RED_SIZE,
		 SDL_GL_GREEN_SIZE,
		 SDL_GL_BLUE_SIZE,
		 SDL_GL_ALPHA_SIZE,
		 SDL_GL_BUFFER_SIZE,
		 SDL_GL_DOUBLEBUFFER,
		 SDL_GL_DEPTH_SIZE,
		 SDL_GL_STENCIL_SIZE,
		 SDL_GL_ACCUM_RED_SIZE,
		 SDL_GL_ACCUM_GREEN_SIZE,
		 SDL_GL_ACCUM_BLUE_SIZE,
		 SDL_GL_ACCUM_ALPHA_SIZE,
		 SDL_GL_STEREO,
		 SDL_GL_MULTISAMPLEBUFFERS,
		 SDL_GL_MULTISAMPLESAMPLES,
		 SDL_GL_ACCELERATED_VISUAL,
		 SDL_GL_RETAINED_BACKING,
		 SDL_GL_CONTEXT_MAJOR_VERSION,
		 SDL_GL_CONTEXT_MINOR_VERSION,
		 SDL_GL_CONTEXT_EGL,
		 SDL_GL_CONTEXT_FLAGS,
		 SDL_GL_CONTEXT_PROFILE_MASK,
		 SDL_GL_SHARE_WITH_CURRENT_CONTEXT,
		 SDL_GL_FRAMEBUFFER_SRGB_CAPABLE,
		 SDL_GL_CONTEXT_RELEASE_BEHAVIOR,
		 SDL_GL_CONTEXT_RESET_NOTIFICATION,
		 SDL_GL_CONTEXT_NO_ERROR,
		 SDL_GL_FLOATBUFFERS,
	} SDL_GLattr;

	void* SDL_CreateWindow(const char *title, int x, int y, int w, int h, unsigned int flags);
	void SDL_DestroyWindow(void *window);

	int SDL_GL_SetAttribute(SDL_GLattr attr, int value);

	void* SDL_GL_CreateContext(void *window);
	void SDL_GL_DeleteContext(void *context);

	int SDL_GL_MakeCurrent(void *window);
	void SDL_GL_SwapWindow(void *window);
]])

return {
	SDL_GL_RED_SIZE = 0,
	SDL_GL_GREEN_SIZE = 1,
	SDL_GL_BLUE_SIZE = 2,
	SDL_GL_ALPHA_SIZE = 3,
	SDL_GL_BUFFER_SIZE = 4,
	SDL_GL_DOUBLEBUFFER = 5,
	SDL_GL_DEPTH_SIZE = 6,
	SDL_GL_STENCIL_SIZE = 7,
	SDL_GL_ACCUM_RED_SIZE = 8,
	SDL_GL_ACCUM_GREEN_SIZE = 9,
	SDL_GL_ACCUM_BLUE_SIZE = 10,
	SDL_GL_ACCUM_ALPHA_SIZE = 11,
	SDL_GL_STEREO = 12,
	SDL_GL_MULTISAMPLEBUFFERS = 13,
	SDL_GL_MULTISAMPLESAMPLES = 14,
	SDL_GL_ACCELERATED_VISUAL = 15,
	SDL_GL_RETAINED_BACKING = 16,
	SDL_GL_CONTEXT_MAJOR_VERSION = 17,
	SDL_GL_CONTEXT_MINOR_VERSION = 18,
	SDL_GL_CONTEXT_EGL = 19,
	SDL_GL_CONTEXT_FLAGS = 20,
	SDL_GL_CONTEXT_PROFILE_MASK = 21,
	SDL_GL_SHARE_WITH_CURRENT_CONTEXT = 22,
	SDL_GL_FRAMEBUFFER_SRGB_CAPABLE = 23,
	SDL_GL_CONTEXT_RELEASE_BEHAVIOR = 24,
	SDL_GL_CONTEXT_RESET_NOTIFICATION = 25,
	SDL_GL_CONTEXT_NO_ERROR = 26,
	SDL_GL_FLOATBUFFERS = 27,

	SDL_GL_CONTEXT_PROFILE_CORE = 0x0001,
	SDL_GL_CONTEXT_PROFILE_COMPATIBILITY = 0x0002,
	SDL_GL_CONTEXT_PROFILE_ES = 0x0004,

	SDL_WINDOW_FULLSCREEN = 0x00000001,
	SDL_WINDOW_OPENGL = 0x00000002,
	SDL_WINDOW_SHOWN = 0x00000004,
	SDL_WINDOW_HIDDEN = 0x00000008,
	SDL_WINDOW_BORDERLESS = 0x00000010,
	SDL_WINDOW_RESIZABLE = 0x00000020,
	SDL_WINDOW_MINIMIZED = 0x00000040,
	SDL_WINDOW_MAXIMIZED = 0x00000080,
	SDL_WINDOW_MOUSE_GRABBED = 0x00000100,
	SDL_WINDOW_INPUT_FOCUS = 0x00000200,
	SDL_WINDOW_MOUSE_FOCUS = 0x00000400,
	SDL_WINDOW_FULLSCREEN_DESKTOP = bit.bor(0x00000001, 0x00001000),
	SDL_WINDOW_FOREIGN = 0x00000800,
	SDL_WINDOW_ALLOW_HIGHDPI = 0x00002000,

	SDL_WINDOW_MOUSE_CAPTURE    = 0x00004000,
	SDL_WINDOW_ALWAYS_ON_TOP    = 0x00008000,
	SDL_WINDOW_SKIP_TASKBAR     = 0x00010000,
	SDL_WINDOW_UTILITY          = 0x00020000,
	SDL_WINDOW_TOOLTIP          = 0x00040000,
	SDL_WINDOW_POPUP_MENU       = 0x00080000,
	SDL_WINDOW_KEYBOARD_GRABBED = 0x00100000,
	-- SDL_WINDOW_VULKAN           = 0x10000000,
	-- SDL_WINDOW_METAL            = 0x20000000,

	SDL_WINDOW_INPUT_GRABBED = 0x00000100
}
